# Site settings
title: IQDent | Tratamente dentare inteligente.
description: Implant dentar 250 de euro. Oferte implant dentar dr Irina Alexandru.
baseurl: "" # the subpath of your site, e.g. /blog
url: www.dririnaalexandru.ro # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: IQDent
    hero_description: Tratamente dentare inteligente.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 0766 748971
    email: alexandru.irina@gmail.com
    address: Bdul Octavian Goga Nr 21, Sector 3, Bucuresti

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 09:00 – 13:00
sunday: inchis

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Bdul Octavian Goga Nr 21, Sector 3, Bucuresti
    address_details: svg/min/logo.svg

# Social settings
facebook: https://facebook.com/dririnaalexandru
twitter: http://twitter.com
instagram: http://instagram.com
feed: yes

# Footer
copyright: © 2015 IQDent - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
