# Site settings
title: INODent - ex IQDent | Tratamente dentare inteligente - Cabinet Stomatologic Nerva Traian, Bucuresti.
description: Implant dentar pret 250 de euro. Oferte implant dentar Dr. Irina Alexandru.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.dririnaalexandru.ro # the name of your domain
logo_url: /favicon.png


name: INODent

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: INODent - ex IQDent
    hero_description: Tratamente dentare inovative.

# Contact form
api_token: be4d9d546a4bc4f5fb27cd142eff4336

# Contact info
contact:
    phone: 0754 523 624
    email: dririnaalexandru@gmail.com
    address: Bulevardul Octavian Goga Nr 21, Bl M103, Sc 2, Ap 37, Interfon 37, Sector 3, București

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 09:00 – 13:00
sunday: inchis

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Bdul Octavian Goga Nr 21, Sector 3, Bucuresti
    address_details: svg/min/logo.svg

# Social settings
facebook: https://facebook.com/dririnaalexandru
twitter: http://twitter.com
instagram: http://instagram.com
feed: yes

# Footer
copyright: © 2015 INODent - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: UA-85822108-1
google_verification: 


#gems:
#    - jekyll-sitemap
